### ISSUE TITLE
Map of objects is not supported by http.post

### ISSUE THREAD

**Issue by k0shk0sh** [supabase-community/functions-dart#1]
Hi there, 
Thanks alot for implementing this quickly on dart. 

I have a function that accepts
```json
{
    "creator": {
        "id": "id",
        "name": "Kosh ",
        "picture": ""
    },
    "receiver": {
        "id": "id",
        "name": "Kosh2 ",
        "picture": ""
    },
    "notificationType": "FOLLOW",
    "body": "",
    "challengeId": "",
    "notificationId": ""
}
```

while calling `function.invoke(body:  myObject.toMap())` throws an error and after following the source of the error I found that dart `http` does not really support `Map<String, dynamic>` however only accepts `Map<String, String>` which resulted in an error that is hard to figure. 

the solution was to create an extension on Functions and do below: 

```dart 
extension BoltsFunction on FunctionsClient {
  Future<FunctionResponse> stringInvoke(
    String url,
    String functionName, {
    required Map<String, String> headers,
    required String body,
  }) async {
    try {
      final response = await http.post(
        Uri.parse('$url/$functionName'),
        headers: headers,
        body: body,
      );

      dynamic data = json.decode(response.body);
      return FunctionResponse(data: data);
    } catch (error) {
      return FunctionResponse(error: error);
    }
  }
}
```

And body in here is just a 
```dart
json.encode({
      'receiver': receiver.toShortMap(),
      'creator': creator.toShortMap(),
      'notificationId': notificationId,
      'challengeId': challengeId,
      'body': body,
      'notificationType': notificationType.name,
    })
```

I will open a PR that fixes this and instead of using `map<String, dynamic>` we should accept `dynamic` allowing callers to determine the type themselves. 

here is what http does eventually with body. 

```dart
if (body != null) {
      if (body is String) {
        request.body = body;
      } else if (body is List) {
        request.bodyBytes = body.cast<int>();
      } else if (body is Map) {
        request.bodyFields = body.cast<String, String>();
      } else {
        throw ArgumentError('Invalid request body "$body".');
      }
    }
```

**Comment by dshukertjr** [comment]
@k0shk0sh So sorry for not being able to look at this issue and the PR you have created. Hopefully [this PR](https://github.com/supabase-community/functions-dart/pull/3) fixes the issue you are having.
